### ISSUE TITLE
Add additional voting statistics for planning poker feature

### ISSUE THREAD

**Issue by oxffaa** [dyatlov-a/Inc.TeamAssistant#41]
As a facilitator, I want to view voting statistics and vote distribution, so that it lets me to make decisions about voting and select participants for discussion quickly and easily.

I would like to view such statistics as:
- mean estimate (implemented already)
- median estimate
- vote distribution (perhaps a histogram, with percentage for each estimate and voted participants)

![Common - Browser](https://github.com/dyatlov-a/Inc.TeamAssistant/assets/9650543/056f0998-216f-4608-a0e6-d76574af3edc)

**Comment by dyatlov-a** [comment]
Thank you for your great idea. I will work on a solution.

**Comment by dyatlov-a** [comment]
I have implemented your idea and will be presenting the solution in the next assessment session.

**Comment by dyatlov-a** [comment]
I have implemented your idea and will be presenting the solution in the next assessment session.
