### ISSUE TITLE
Draft review

### ISSUE THREAD

**Issue by R-aa-ff-aa** [dyatlov-a/Inc.TeamAssistant#59]
As a developer, before sending review request to the developer's chat I want to see draft review request in order to check reviewer's nickname if it was specified and review message itself.

After getting draft review request it would be nice to have command buttons. I suggest following options:

-send review request (in case if everything is alright from developer's perspective)
-edit review request (in case if something is incorrect in request message)
-cancel (if developer decided that he doesn't need review anymore)

**Comment by dyatlov-a** [comment]
Thank you for your idea. I have added a preview for the review tasks. Could you please check the implementation and provide your feedback?
